
import { Product } from "@/lib/actions/products"

export const DEMO_DATA: Record<string, Product[]> = {
    fashion: [
        {
            id: "f1",
            name: "Silk Evening Gown",
            description: "Elegant floor-length silk gown suitable for formal events. Features a deep V-neckline and open back design.",
            price: 1299.00,
            sku: "FAS-001",
            images: ["https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=2883&auto=format&fit=crop"],
            image_url: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=2883&auto=format&fit=crop",
            category: "Dresses",
            stock: 10,
            user_id: "demo",
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            order: 0,
            product_url: null,
            custom_attributes: [{ name: "currency", value: "USD", unit: "" }, { name: "Material", value: "100% Silk", unit: "" }]
        },
        {
            id: "f2",
            name: "Structured Blazer",
            description: "Modern cut structured blazer in midnight blue. Perfect for both office and evening wear.",
            price: 450.00,
            sku: "FAS-002",
            images: ["https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=2836&auto=format&fit=crop"],
            image_url: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=2836&auto=format&fit=crop",
            category: "Outerwear",
            stock: 15,
            user_id: "demo",
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            order: 1,
            product_url: null,
            custom_attributes: [{ name: "currency", value: "USD", unit: "" }, { name: "Fit", value: "Slim", unit: "" }]
        },
        {
            id: "f3",
            name: "Leather Ankle Boots",
            description: "Hand-crafted Italian leather boots with a comfortable block heel.",
            price: 320.00,
            sku: "FAS-003",
            images: ["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=2960&auto=format&fit=crop"],
            image_url: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=2960&auto=format&fit=crop",
            category: "Shoes",
            stock: 8,
            user_id: "demo",
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            order: 2,
            product_url: null,
            custom_attributes: [{ name: "currency", value: "USD", unit: "" }, { name: "Material", value: "Leather", unit: "" }]
        },
        {
            id: "f4",
            name: "Cashmere Scarf",
            description: "Luxuriously soft cashmere scarf in neutral beige tone.",
            price: 180.00,
            sku: "FAS-004",
            images: ["https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?q=80&w=2787&auto=format&fit=crop"],
            image_url: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?q=80&w=2787&auto=format&fit=crop",
            category: "Accessories",
            stock: 25,
            user_id: "demo",
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            order: 3,
            product_url: null,
            custom_attributes: [{ name: "currency", value: "USD", unit: "" }, { name: "Material", value: "Cashmere", unit: "" }]
        },
        {
            id: "f5",
            name: "Designer Handbag",
            description: "Classic silhouette handbag with gold hardware and spacious interior.",
            price: 2400.00,
            sku: "FAS-005",
            images: ["https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=2835&auto=format&fit=crop"],
            image_url: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=2835&auto=format&fit=crop",
            category: "Bags",
            stock: 5,
            user_id: "demo",
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            order: 4,
            product_url: null,
            custom_attributes: [{ name: "currency", value: "USD", unit: "" }, { name: "Color", value: "Black", unit: "" }]
        },
        {
            id: "f6",
            name: "Statement Necklace",
            description: "Bold gold-plated necklace with intricate detailing.",
            price: 150.00,
            sku: "FAS-006",
            images: ["https://images.unsplash.com/photo-1599643478518-17488fbbcd75?q=80&w=2787&auto=format&fit=crop"],
            image_url: "https://images.unsplash.com/photo-1599643478518-17488fbbcd75?q=80&w=2787&auto=format&fit=crop",
            category: "Jewelry",
            stock: 30,
            user_id: "demo",
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            order: 5,
            product_url: null,
            custom_attributes: [{ name: "currency", value: "USD", unit: "" }, { name: "Material", value: "Gold Plated", unit: "" }]
        }
    ],
    tech: [
        {
            id: "t1",
            name: "Pro Noise-Canceling Headphones",
            description: "Immersive sound with industry-leading noise cancellation technology.",
            price: 349.99,
            sku: "TEC-001",
            images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=2940&auto=format&fit=crop"],
            image_url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=2940&auto=format&fit=crop",
            category: "Audio",
            stock: 50,
            user_id: "demo",
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            order: 0,
            product_url: null,
            custom_attributes: [{ name: "currency", value: "USD", unit: "" }, { name: "Battery", value: "30h", unit: "" }]
        },
        {
            id: "t2",
            name: "UltraCheck Smartwatch",
            description: "Advanced health monitoring, fitness tracking, and seamless connectivity.",
            price: 399.00,
            sku: "TEC-002",
            images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=2899&auto=format&fit=crop"],
            image_url: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=2899&auto=format&fit=crop",
            category: "Wearables",
            stock: 40,
            user_id: "demo",
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            order: 1,
            product_url: null,
            custom_attributes: [{ name: "currency", value: "USD", unit: "" }, { name: "Water Resist", value: "50m", unit: "" }]
        },
        {
            id: "t3",
            name: "Mirrorless Camera Kit",
            description: "Professional grade mirrorless camera with 24-70mm lens kit.",
            price: 1899.00,
            sku: "TEC-003",
            images: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=2800&auto=format&fit=crop"],
            image_url: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=2800&auto=format&fit=crop",
            category: "Photography",
            stock: 12,
            user_id: "demo",
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            order: 2,
            product_url: null,
            custom_attributes: [{ name: "currency", value: "USD", unit: "" }, { name: "Resolution", value: "24MP", unit: "" }]
        },
        {
            id: "t4",
            name: "Mechanical Keyboard",
            description: "RGB backlit mechanical keyboard with tactile switches for ultimate typing experience.",
            price: 129.00,
            sku: "TEC-004",
            images: ["https://images.unsplash.com/photo-1587829741301-3dc89de69c3f?q=80&w=2942&auto=format&fit=crop"],
            image_url: "https://images.unsplash.com/photo-1587829741301-3dc89de69c3f?q=80&w=2942&auto=format&fit=crop",
            category: "Peripherals",
            stock: 200,
            user_id: "demo",
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            order: 3,
            product_url: null,
            custom_attributes: [{ name: "currency", value: "USD", unit: "" }, { name: "Switch", value: "Brown", unit: "" }]
        },
        {
            id: "t5",
            name: "Wireless Mouse",
            description: "Ergonomic wireless mouse with precision tracking and long battery life.",
            price: 79.00,
            sku: "TEC-005",
            images: ["https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?q=80&w=2934&auto=format&fit=crop"],
            image_url: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?q=80&w=2934&auto=format&fit=crop",
            category: "Peripherals",
            stock: 150,
            user_id: "demo",
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            order: 4,
            product_url: null,
            custom_attributes: [{ name: "currency", value: "USD", unit: "" }, { name: "DPI", value: "16000", unit: "" }]
        },
        {
            id: "t6",
            name: "Portable SSD 1TB",
            description: "High-speed portable solid state drive, shock resistant and secure.",
            price: 119.00,
            sku: "TEC-006",
            images: ["https://images.unsplash.com/photo-1597872258083-ef52749e48f4?q=80&w=2940&auto=format&fit=crop"],
            image_url: "https://images.unsplash.com/photo-1597872258083-ef52749e48f4?q=80&w=2940&auto=format&fit=crop",
            category: "Storage",
            stock: 80,
            user_id: "demo",
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            order: 5,
            product_url: null,
            custom_attributes: [{ name: "currency", value: "USD", unit: "" }, { name: "Capacity", value: "1TB", unit: "" }]
        }
    ],
    cosmetic: [
        {
            id: "c1",
            name: "Hydrating Facial Serum",
            description: "Intense hydration serum with hyaluronic acid and vitamin C.",
            price: 45.00,
            sku: "COS-001",
            images: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=2787&auto=format&fit=crop"],
            image_url: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=2787&auto=format&fit=crop",
            category: "Skincare",
            stock: 100,
            user_id: "demo",
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            order: 0,
            product_url: null,
            custom_attributes: [{ name: "currency", value: "USD", unit: "" }, { name: "Volume", value: "30ml", unit: "" }]
        },
        {
            id: "c2",
            name: "Matte Lipstick Set",
            description: "Long-lasting matte lipstick set in 5 vibrant shades.",
            price: 32.00,
            sku: "COS-002",
            images: ["https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=2915&auto=format&fit=crop"],
            image_url: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=2915&auto=format&fit=crop",
            category: "Makeup",
            stock: 200,
            user_id: "demo",
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            order: 1,
            product_url: null,
            custom_attributes: [{ name: "currency", value: "USD", unit: "" }, { name: "Shades", value: "5", unit: "" }]
        },
        {
            id: "c3",
            name: "Luxury Perfume",
            description: "Signature floral scent with notes of jasmine and rose.",
            price: 120.00,
            sku: "COS-003",
            images: ["https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=2804&auto=format&fit=crop"],
            image_url: "https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=2804&auto=format&fit=crop",
            category: "Fragrance",
            stock: 50,
            user_id: "demo",
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            order: 2,
            product_url: null,
            custom_attributes: [{ name: "currency", value: "USD", unit: "" }, { name: "Volume", value: "50ml", unit: "" }]
        },
        {
            id: "c4",
            name: "Organic Body Oil",
            description: "Nourishing body oil made with 100% organic ingredients.",
            price: 28.00,
            sku: "COS-004",
            images: ["https://images.unsplash.com/photo-1608248597279-f99d160bfbc8?q=80&w=2787&auto=format&fit=crop"],
            image_url: "https://images.unsplash.com/photo-1608248597279-f99d160bfbc8?q=80&w=2787&auto=format&fit=crop",
            category: "Body Care",
            stock: 80,
            user_id: "demo",
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            order: 3,
            product_url: null,
            custom_attributes: [{ name: "currency", value: "USD", unit: "" }, { name: "Type", value: "Organic", unit: "" }]
        },
        {
            id: "c5",
            name: "Eye Shadow Palette",
            description: "Highly pigmented eye shadow palette with 12 distinct colors.",
            price: 55.00,
            sku: "COS-005",
            images: ["https://images.unsplash.com/photo-1512496015851-a90fb38ba796?q=80&w=2835&auto=format&fit=crop"],
            image_url: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?q=80&w=2835&auto=format&fit=crop",
            category: "Makeup",
            stock: 120,
            user_id: "demo",
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            order: 4,
            product_url: null,
            custom_attributes: [{ name: "currency", value: "USD", unit: "" }, { name: "Finish", value: "Shimmer", unit: "" }]
        },
        {
            id: "c6",
            name: "Anti-Aging Cream",
            description: "Advanced formula night cream to reduce fine lines and wrinkles.",
            price: 85.00,
            sku: "COS-006",
            images: ["https://images.unsplash.com/photo-1616683693504-3ea7e9ad6fec?q=80&w=2787&auto=format&fit=crop"],
            image_url: "https://images.unsplash.com/photo-1616683693504-3ea7e9ad6fec?q=80&w=2787&auto=format&fit=crop",
            category: "Skincare",
            stock: 60,
            user_id: "demo",
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            order: 5,
            product_url: null,
            custom_attributes: [{ name: "currency", value: "USD", unit: "" }, { name: "Benefits", value: "Anti-Aging", unit: "" }]
        }
    ]
}
