export const SYSTEM_FIELDS_KEYS = ['name', 'sku', 'description', 'price', 'stock', 'category', 'image_url', 'product_url'] as const

export const ROWS_PER_PAGE = 100

export const HEADER_ALIASES: Record<string, string> = {
    ad: 'name',
    isim: 'name',
    adi: 'name',
    adı: 'name',
    'ürün adı': 'name',
    'urun adi': 'name',
    'ürün_adı': 'name',
    urun_adi: 'name',
    ürünadı: 'name',
    urunadi: 'name',
    ürün: 'name',
    urun: 'name',
    name: 'name',
    'product name': 'name',
    product_name: 'name',
    productname: 'name',
    başlık: 'name',
    baslik: 'name',
    title: 'name',
    sku: 'sku',
    'stok kodu': 'sku',
    stok_kodu: 'sku',
    stokkodu: 'sku',
    kod: 'sku',
    'ürün kodu': 'sku',
    'urun kodu': 'sku',
    ürün_kodu: 'sku',
    urun_kodu: 'sku',
    'product code': 'sku',
    product_code: 'sku',
    productcode: 'sku',
    barkod: 'sku',
    barcode: 'sku',
    açıklama: 'description',
    aciklama: 'description',
    detay: 'description',
    description: 'description',
    desc: 'description',
    bilgi: 'description',
    'ürün açıklaması': 'description',
    'urun aciklamasi': 'description',
    fiyat: 'price',
    ücret: 'price',
    ucret: 'price',
    tutar: 'price',
    price: 'price',
    'birim fiyat': 'price',
    birim_fiyat: 'price',
    'satış fiyatı': 'price',
    'satis fiyati': 'price',
    satis_fiyati: 'price',
    amount: 'price',
    stok: 'stock',
    adet: 'stock',
    miktar: 'stock',
    stock: 'stock',
    quantity: 'stock',
    qty: 'stock',
    'stok adedi': 'stock',
    stok_adedi: 'stock',
    kategori: 'category',
    category: 'category',
    grup: 'category',
    tür: 'category',
    tur: 'category',
    type: 'category',
    'ürün kategorisi': 'category',
    'urun kategorisi': 'category',
    görsel: 'image_url',
    gorsel: 'image_url',
    'görsel url': 'image_url',
    'gorsel url': 'image_url',
    görsel_url: 'image_url',
    gorsel_url: 'image_url',
    resim: 'image_url',
    'resim url': 'image_url',
    resim_url: 'image_url',
    image: 'image_url',
    image_url: 'image_url',
    imageurl: 'image_url',
    photo: 'image_url',
    foto: 'image_url',
    fotoğraf: 'image_url',
    fotograf: 'image_url',
    'ürün url': 'product_url',
    'urun url': 'product_url',
    ürün_url: 'product_url',
    urun_url: 'product_url',
    'ürün linki': 'product_url',
    'urun linki': 'product_url',
    'product url': 'product_url',
    product_url: 'product_url',
    'product link': 'product_url',
    link: 'product_url',
    url: 'product_url',
}
